import './globals.css';
import styles from './layout.module.css';
import { JetBrains_Mono } from 'next/font/google';

const font = JetBrains_Mono({ subsets: ['latin'] });

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
        <div className={styles.head}>RootLayout</div>
        <div className={styles.content}>{children}</div>
      </body>
    </html>
  );
}
